{{- if and (not .Values.externalSecret) (.Values.config.generate) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rauthy.fullname" . }}-config
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "rauthy.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.toml: |-
    [server]
    scheme = {{ .Values.service.scheme | quote }}
    pub_url = {{ include "rauthy.domainName" . | quote }}
    {{- if gt (len .Values.config.trustedProxies) 0 }}
    proxy_mode = true
    trusted_proxies = [
      {{- range .Values.config.trustedProxies }}
      "{{ . }}",
      {{- end }}
    ]
    {{- end }}
    {{- if .Values.metrics.enabled }}
    metrics_enable = true
    metrics_port = {{ int .Values.metrics.port }}
    {{- end }}

    [cluster]
    node_id_from = "k8s"
    {{- $root := . }}
    {{- $headless := include "rauthy.fullname" . | printf "%s-headless" }}
    {{- if gt (int .Values.replicaCount) 1 }}
    nodes = [
      {{- range $i, $ := until (int $root.Values.replicaCount) }}
        "{{ add $i 1 }} {{ $root.Release.Name }}-{{ $i }}.{{ $headless }}:{{ $root.Values.headlessService.ports.raft }} {{ $root.Release.Name }}-{{ $i }}.{{ $headless }}:{{ $root.Values.headlessService.ports.api }}",
      {{- end }}
    ]
    {{- else }}
    nodes = [
        "1 localhost:{{ $root.Values.headlessService.ports.raft }} localhost:{{ $root.Values.headlessService.ports.api }}"
    ]
    log_sync = "immediate"
    {{- end }}
    
    secret_raft = "{{ randAlphaNum 48 }}"
    secret_api = "{{ randAlphaNum 48 }}"

    [encryption]
    {{- $encKeyId := randAlphaNum 6 }}
    keys = [
        "{{ printf "%s/%s" ($encKeyId) (b64enc (randAlphaNum 32)) }}"
    ]
    key_active = "{{ $encKeyId }}"

    [bootstrap]
    admin_email = "admin@localhost"

    [webauthn]
    rp_id = {{ include "rauthy.domainName" . | quote }}
    rp_origin = {{ include "rauthy.rpOrigin" . | quote }}
{{- end }}
