apiVersion: v2
name: rauthy
description: A Helm chart for Rauthy
type: application
version: 0.32.5-rc1
appVersion: "0.32.5"
home: https://github.com/sebadob/rauthy
icon: https://sebadob.github.io/rauthy/rauthy_grey_small.png
sources:
  - https://github.com/sebadob/rauthy
  - https://github.com/Reversing0148/rauthy-helm
keywords:
  - authentication
  - authorization
  - oidc
  - openid-connect
  - sso
  - single-sign-on
  - identity
  - rust
maintainers:
  - name: Reversing0148
    url: https://github.com/Reversing0148
kubeVersion: ">=1.19.0-0"
annotations:
  category: Authentication
  licenses: Apache-2.0
